//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_GMEDINA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTravelDetail
    {
        public int travel_Detail_ID { get; set; }
        public int travel_ID { get; set; }
        public int employee_ID { get; set; }
        public decimal distance_Kilometers { get; set; }
        public decimal travel_Cost { get; set; }
    
        public virtual tbEmployee tbEmployee { get; set; }
        public virtual tbTravel tbTravel { get; set; }
    }
}
