//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_GMEDINA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTravel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbTravel()
        {
            this.tbTravelDetails = new HashSet<tbTravelDetail>();
        }
    
        public int travel_ID { get; set; }
        public int subsidiary_ID { get; set; }
        public int transporter_ID { get; set; }
        public int employee_ID { get; set; }
        public System.DateTime departure_Date_and_Time { get; set; }
        public decimal distance_Kilometers { get; set; }
        public decimal total_travel_Cost { get; set; }
    
        public virtual tbEmployee tbEmployee { get; set; }
        public virtual tbSubsidiary tbSubsidiary { get; set; }
        public virtual tbTransporter tbTransporter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbTravelDetail> tbTravelDetails { get; set; }
    }
}
