//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_GMEDINA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUser
    {
        public int user_ID { get; set; }
        public int employee_ID { get; set; }
        public string user_Username { get; set; }
        public byte[] user_Password { get; set; }
        public System.Guid user_Token { get; set; }
        public bool user_IsActive { get; set; }
        public bool user_IsAdmin { get; set; }
    
        public virtual tbEmployee tbEmployee { get; set; }
    }
}
